/**
 * movie-list.js
 *
 *  - id: String, a unique identifier (e.g., "P1", "P2")
 *  - title: String, title of the movie
 *  - trailer: Boolean, has trailer
 *  - showtimes: Boolean, has list of showtimes available
 *  - advance: Boolean, has advance ticket option available
 *  - tickets: Boolean, has ticket option available
 *  - date: String, date of release
 *  - special: Boolean, in special presentation list
 *  - imageUrl: String, url link to the poster image
 */

window.movies = [
  {
    id: "31841_320_470",
    title: "The Bad Guys",
    trailer: true,
    showtimes: false,
    advance: false,
    tickets: true,
    date: "",
    special: false,
    imageUrl: "img/31841_320_470.jpg",
    category: ["all", "now"],
  },
  {
    id: "33718_320_470",
    title: "Memory",
    trailer: true,
    showtimes: false,
    advance: false,
    tickets: true,
    date: "",
    special: false,
    imageUrl: "img/33718_320_470.jpg",
    category: ["all", "now"],
  },
  {
    id: "28837_320_470",
    title: "Doctor Strange In The Multiverse Of Madness",
    trailer: true,
    showtimes: false,
    advance: true,
    tickets: false,
    date: "Thu, May 5, 2022",
    special: false,
    imageUrl: "img/28837_320_470.jpg",
    category: ["all", "soon"],
  },
  {
    id: "28787_320_470",
    title: "Jurassic World Dominion",
    trailer: true,
    showtimes: false,
    advance: true,
    tickets: false,
    date: "Thu, Jun 9, 2022",
    special: false,
    imageUrl: "img/28787_320_470.jpg",
    category: ["all", "soon"],
  },
  {
    id: "34065_320_470",
    title: "JURASSIC WORLD DOMINION IMAX exclusive Live Q&A with Special Guests",
    trailer: false,
    showtimes: false,
    advance: true,
    tickets: false,
    date: "Thu, Jun 9, 2022",
    special: false,
    imageUrl: "img/34065_320_470.jpg",
    category: ["all", "soon"],
  },
  {
    id: "34011_320_470",
    title: "DOWNTON ABBEY: A NEW ERA EARLY ACCESS",
    trailer: false,
    showtimes: false,
    advance: true,
    tickets: false,
    date: "Wed, May 18, 2022",
    special: false,
    imageUrl: "img/34011_320_470.jpg",
    category: ["all", "soon"],
  },
  {
    id: "34011_320_471",
    title: "Downton Abbey: A New Era",
    trailer: true,
    showtimes: false,
    advance: true,
    tickets: false,
    date: "Thu, May 19, 2022",
    special: false,
    imageUrl: "img/34011_320_470.jpg",
    category: ["all", "soon"],
  },
  {
    id: "27669_320_470",
    title: "Top Gun: Maverick",
    trailer: true,
    showtimes: false,
    advance: false,
    tickets: false,
    date: "",
    special: false,
    imageUrl: "img/27669_320_470.jpg",
    category: ["all", "now"],
  },
  {
    id: "33288_320_470",
    title: "The Northman",
    trailer: true,
    showtimes: false,
    advance: false,
    tickets: true,
    date: "",
    special: false,
    imageUrl: "img/33288_320_470.jpg",
    category: ["all", "now"],
  },
  {
    id: "32632_320_470",
    title: "Sonic The Hedgehog 2",
    trailer: true,
    showtimes: false,
    advance: false,
    tickets: true,
    date: "",
    special: false,
    imageUrl: "img/32632_320_470.jpg",
    category: ["all", "now"],
  },
  {
    id: "34018_320_470",
    title: "Singin' In The Rain",
    trailer: false,
    showtimes: true,
    advance: false,
    tickets: false,
    date: "",
    special: true,
    imageUrl: "img/34018_320_470.jpg"
  },
  {
    id: "33927_320_470",
    title: "The Lady of Heaven",
    trailer: true,
    showtimes: true,
    advance: false,
    tickets: false,
    date: "",
    special: true,
    imageUrl: "img/33927_320_470.jpg"
  },
  {
    id: "34028_320_470",
    title: "This Much I Know To Be True",
    trailer: true,
    showtimes: false,
    advance: true,
    tickets: false,
    date: "Wed, May 11, 2022",
    special: true,
    imageUrl: "img/34028_320_470.jpg"
  },
  {
    id: "34003_320_470",
    title: "ABBA: The Movie - Fan Event",
    trailer: false,
    showtimes: false,
    advance: true,
    tickets: false,
    date: "Thu, May 12, 2022",
    special: true,
    imageUrl: "img/34003_320_470.jpg"
  },
  {
    id: "34019_320_470",
    title: "Twenty One Pilots Cinema Experience",
    trailer: false,
    showtimes: false,
    advance: true,
    tickets: false,
    date: "Thu, May 19, 2022",
    special: true,
    imageUrl: "img/34019_320_470.jpg"
  },
  {
    id: "34013_320_470",
    title: "Pompo the Cinephile",
    trailer: false,
    showtimes: true,
    advance: false,
    tickets: false,
    date: "",
    special: true,
    imageUrl: "img/34013_320_470.jpg"
  },
  {
    id: "34013_320_471",
    title: "Pompo the Cinephile (Japanese w/e.s.t.)",
    trailer: false,
    showtimes: true,
    advance: false,
    tickets: false,
    date: "",
    special: true,
    imageUrl: "img/postermissing_460x682.jpg"
  },
  {
    id: "33854_320_470",
    title: "Charlotte",
    trailer: false,
    showtimes: false,
    advance: false,
    tickets: true,
    date: "",
    special: true,
    imageUrl: "img/33854_320_470.jpg"
  },
  {
    id: "33585_320_470",
    title: "The Lost City",
    trailer: true,
    showtimes: false,
    advance: false,
    tickets: true,
    date: "",
    special: true,
    imageUrl: "img/33585_320_470.jpg"
  },
];
