window.cityList = [
    { prov: "AB", city: "Banff" },
    { prov: "AB", city: "Brooks" },
    { prov: "AB", city: "Calgary" },
    { prov: "AB", city: "Edmonton" },
    { prov: "AB", city: "Fort McMurray" },
    { prov: "AB", city: "Grande Prairie" },
    { prov: "AB", city: "Jasper" },
    { prov: "AB", city: "Lake Louise" },
    { prov: "AB", city: "Lethbridge" },
    { prov: "AB", city: "Medicine Hat" },
    { prov: "AB", city: "Red Deer" },
    { prov: "AB", city: "Saint Albert" },

    { prov: "BC", city: "Barkerville" },
    { prov: "BC", city: "Burnaby" },
    { prov: "BC", city: "Campbell River" },
    { prov: "BC", city: "Chilliwack" },
    { prov: "BC", city: "Courtenay" },
    { prov: "BC", city: "Cranbrook" },
    { prov: "BC", city: "Dawson Creek" },
    { prov: "BC", city: "Delta" },
    { prov: "BC", city: "Esquimalt" },
    { prov: "BC", city: "Fort Saint James" },
    { prov: "BC", city: "Fort Saint John" },
    { prov: "BC", city: "Hope" },
    { prov: "BC", city: "Kamloops" },
    { prov: "BC", city: "Kelowna" },
    { prov: "BC", city: "Kimberley" },
    { prov: "BC", city: "Kitimat" },
    { prov: "BC", city: "Langley" },
    { prov: "BC", city: "Nanaimo" },
    { prov: "BC", city: "Nelson" },
    { prov: "BC", city: "New Westminster" },
    { prov: "BC", city: "North Vancouver" },
    { prov: "BC", city: "Oak Bay" },
    { prov: "BC", city: "Penticton" },
    { prov: "BC", city: "Powell River" },
    { prov: "BC", city: "Prince George" },
    { prov: "BC", city: "Prince Rupert" },
    { prov: "BC", city: "Quesnel" },
    { prov: "BC", city: "Revelstoke" },
    { prov: "BC", city: "Rossland" },
    { prov: "BC", city: "Trail" },
    { prov: "BC", city: "Vancouver" },
    { prov: "BC", city: "Vernon" },
    { prov: "BC", city: "Victoria" },
    { prov: "BC", city: "West Vancouver" },
    { prov: "BC", city: "White Rock" },

    { prov: "MB", city: "Brandon" },
    { prov: "MB", city: "Churchill" },
    { prov: "MB", city: "Dauphin" },
    { prov: "MB", city: "Flin Flon" },
    { prov: "MB", city: "Kildonan" },
    { prov: "MB", city: "Saint Boniface" },
    { prov: "MB", city: "Swan River" },
    { prov: "MB", city: "Thompson" },
    { prov: "MB", city: "Winnipeg" },
    { prov: "MB", city: "York Factory" },

    { prov: "NB", city: "Bathurst" },
    { prov: "MB", city: "Caraquet" },
    { prov: "MB", city: "Dalhousie" },
    { prov: "MB", city: "Fredericton" },
    { prov: "MB", city: "Miramichi" },
    { prov: "MB", city: "Moncton" },
    { prov: "MB", city: "Saint John" },

    { prov: "NL", city: "Argentia" },
    { prov: "NL", city: "Bonavista" },
    { prov: "NL", city: "Channel-Port aux Basques" },
    { prov: "NL", city: "Corner Brook" },
    { prov: "NL", city: "Ferryland" },
    { prov: "NL", city: "Gander" },
    { prov: "NL", city: "Grand Falls–Windsor" },
    { prov: "NL", city: "Happy Valley–Goose Bay" },
    { prov: "NL", city: "Harbour Grace" },
    { prov: "NL", city: "Labrador City" },
    { prov: "NL", city: "Placentia" },
    { prov: "NL", city: "Saint Anthony" },
    { prov: "NL", city: "St. John’s" },
    { prov: "NL", city: "Wabana" },

    { prov: "NT", city: "Fort Smith" },
    { prov: "NT", city: "Hay River" },
    { prov: "NT", city: "Inuvik" },
    { prov: "NT", city: "Tuktoyaktuk" },
    { prov: "NT", city: "Yellowknife" },

    { prov: "NS", city: "Baddeck" },
    { prov: "NS", city: "Digby" },
    { prov: "NS", city: "Glace Bay" },
    { prov: "NS", city: "Halifax" },
    { prov: "NS", city: "Liverpool" },
    { prov: "NS", city: "Louisbourg" },
    { prov: "NS", city: "Lunenburg" },
    { prov: "NS", city: "Pictou" },
    { prov: "NS", city: "Port Hawkesbury" },
    { prov: "NS", city: "Springhill" },
    { prov: "NS", city: "Sydney" },
    { prov: "NS", city: "Yarmouth" },

    { prov: "NU", city: "Iqaluit" },

    { prov: "ON", city: "Bancroft" },
    { prov: "ON", city: "Barrie" },
    { prov: "ON", city: "Belleville" },
    { prov: "ON", city: "Brampton" },
    { prov: "ON", city: "Brantford" },
    { prov: "ON", city: "Brockville" },
    { prov: "ON", city: "Burlington" },
    { prov: "ON", city: "Cambridge" },
    { prov: "ON", city: "Chatham" },
    { prov: "ON", city: "Chatham-Kent" },
    { prov: "ON", city: "Cornwall" },
    { prov: "ON", city: "Elliot Lake" },
    { prov: "ON", city: "Etobicoke" },
    { prov: "ON", city: "Fort Erie" },
    { prov: "ON", city: "Fort Frances" },
    { prov: "ON", city: "Gananoque" },
    { prov: "ON", city: "Guelph" },
    { prov: "ON", city: "Hamilton" },
    { prov: "ON", city: "Iroquois Falls" },
    { prov: "ON", city: "Kapuskasing" },
    { prov: "ON", city: "Kawartha Lakes" },
    { prov: "ON", city: "Kenora" },
    { prov: "ON", city: "Kingston" },
    { prov: "ON", city: "Kirkland Lake" },
    { prov: "ON", city: "Kitchener" },
    { prov: "ON", city: "Laurentian Hills" },
    { prov: "ON", city: "London" },
    { prov: "ON", city: "Midland" },
    { prov: "ON", city: "Mississauga" },
    { prov: "ON", city: "Moose Factory" },
    { prov: "ON", city: "Moosonee" },
    { prov: "ON", city: "Niagara Falls" },
    { prov: "ON", city: "Niagara-on-the-Lake" },
    { prov: "ON", city: "North Bay" },
    { prov: "ON", city: "North York" },
    { prov: "ON", city: "Oakville" },
    { prov: "ON", city: "Orillia" },
    { prov: "ON", city: "Oshawa" },
    { prov: "ON", city: "Ottawa" },
    { prov: "ON", city: "Parry Sound" },
    { prov: "ON", city: "Perth" },
    { prov: "ON", city: "Peterborough" },
    { prov: "ON", city: "Picton" },
    { prov: "ON", city: "Port Colborne" },
    { prov: "ON", city: "Saint Catharines" },
    { prov: "ON", city: "Saint Thomas" },
    { prov: "ON", city: "Sarnia-Clearwater" },
    { prov: "ON", city: "Sault Sainte Marie" },
    { prov: "ON", city: "Scarborough" },
    { prov: "ON", city: "Simcoe" },
    { prov: "ON", city: "Stratford" },
    { prov: "ON", city: "Sudbury" },
    { prov: "ON", city: "Temiskaming Shores" },
    { prov: "ON", city: "Thorold" },
    { prov: "ON", city: "Thunder Bay" },
    { prov: "ON", city: "Timmins" },
    { prov: "ON", city: "Toronto" },
    { prov: "ON", city: "Trenton" },
    { prov: "ON", city: "Waterloo" },
    { prov: "ON", city: "Welland" },
    { prov: "ON", city: "West Nipissing" },
    { prov: "ON", city: "Windsor" },
    { prov: "ON", city: "Woodstock" },
    { prov: "ON", city: "York" },

    { prov: "PE", city: "Borden" },
    { prov: "PE", city: "Cavendish" },
    { prov: "PE", city: "Charlottetown" },
    { prov: "PE", city: "Souris" },
    { prov: "PE", city: "Summerside" },

    { prov: "QC", city: "Asbestos" },
    { prov: "QC", city: "Baie-Comeau" },
    { prov: "QC", city: "Beloeil" },
    { prov: "QC", city: "Cap-de-la-Madeleine" },
    { prov: "QC", city: "Chambly" },
    { prov: "QC", city: "Charlesbourg" },
    { prov: "QC", city: "Châteauguay" },
    { prov: "QC", city: "Chibougamau" },
    { prov: "QC", city: "Côte-Saint-Luc" },
    { prov: "QC", city: "Dorval" },
    { prov: "QC", city: "Gaspé" },
    { prov: "QC", city: "Gatineau" },
    { prov: "QC", city: "Granby" },
    { prov: "QC", city: "Havre-Saint-Pierre" },
    { prov: "QC", city: "Hull" },
    { prov: "QC", city: "Jonquière" },
    { prov: "QC", city: "Kuujjuaq" },
    { prov: "QC", city: "La Salle" },
    { prov: "QC", city: "La Tuque" },
    { prov: "QC", city: "Lachine" },
    { prov: "QC", city: "Laval" },
    { prov: "QC", city: "Lévis" },
    { prov: "QC", city: "Longueuil" },
    { prov: "QC", city: "Magog" },
    { prov: "QC", city: "Matane" },
    { prov: "QC", city: "Montreal" },
    { prov: "QC", city: "Montréal-Nord" },
    { prov: "QC", city: "Percé" },
    { prov: "QC", city: "Port-Cartier" },
    { prov: "QC", city: "Quebec" },
    { prov: "QC", city: "Rimouski" },
    { prov: "QC", city: "Rouyn-Noranda" },
    { prov: "QC", city: "Saguenay" },
    { prov: "QC", city: "Saint-Eustache" },
    { prov: "QC", city: "Saint-Hubert" },
    { prov: "QC", city: "Sainte-Anne-de-Beaupré" },
    { prov: "QC", city: "Sainte-Foy" },
    { prov: "QC", city: "Sainte-Thérèse" },
    { prov: "QC", city: "Sept-Îles" },
    { prov: "QC", city: "Sherbrooke" },
    { prov: "QC", city: "Sorel-Tracy" },
    { prov: "QC", city: "Trois-Rivières" },
    { prov: "QC", city: "Val-d’Or" },
    { prov: "QC", city: "Waskaganish" },

    { prov: "SK", city: "Batoche" },
    { prov: "SK", city: "Cumberland House" },
    { prov: "SK", city: "Estevan" },
    { prov: "SK", city: "Flin Flon" },
    { prov: "SK", city: "Moose Jaw" },
    { prov: "SK", city: "Prince Albert" },
    { prov: "SK", city: "Regina" },
    { prov: "SK", city: "Saskatoon" },
    { prov: "SK", city: "Uranium City" },

    { prov: "YT", city: "Dawson" },
    { prov: "YT", city: "Watson Lake" },
    { prov: "YT", city: "Whitehorse" },
  ];